language: python
python:
  - '3.4'
  - '3.5'

matrix:
  allow_failures:
    - python: '3.4'

cache:
  pip: true
  directories:
  - eggs/

install:
  - python3 bootstrap.py
  - bin/buildout

script: bin/test

notifications:
  email:
    on_success: never
    on_failure: always
