---
dist: trusty
sudo: false

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

matrix:
  fast_finish: true

cache:
  pip: true
  directories:
    - eggs/

install:
  - pip install -r requirements.txt
  - buildout

script: bin/test

notifications:
  email:
    on_success: change
    on_failure: change
